"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ALERT_TYPES = exports.ALERT_TYPES_ARRAY = exports.ALERTS_POSITION = exports.ALERTS_POSITION_ARRAY = void 0;
const ALERTS_POSITION_ARRAY = ['TOP_CENTER', 'TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_CENTER', 'BOTTOM_LEFT', 'BOTTOM_RIGHT'];
exports.ALERTS_POSITION_ARRAY = ALERTS_POSITION_ARRAY;
const ALERTS_POSITION = {
  TOP_CENTER: 'TOP_CENTER',
  TOP_LEFT: 'TOP_LEFT',
  TOP_RIGHT: 'TOP_RIGHT',
  BOTTOM_CENTER: 'BOTTOM_CENTER',
  BOTTOM_LEFT: 'BOTTOM_LEFT',
  BOTTOM_RIGHT: 'BOTTOM_RIGHT'
};
exports.ALERTS_POSITION = ALERTS_POSITION;
const ALERT_TYPES_ARRAY = ['INFO', 'SUCCESS', 'WARNING', 'ERROR'];
exports.ALERT_TYPES_ARRAY = ALERT_TYPES_ARRAY;
const ALERT_TYPES = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR'
};
exports.ALERT_TYPES = ALERT_TYPES;